export const metadata = {
    title: "Nextify | Profile",
    description: "Generated by create next app",
  };

const Profile = () => {
    return (
        <div className="flex justify-center items-center min-h-[80vh]">
            <h1 className="text-5xl font-bold">Welcome to your profile!</h1>
        </div>
    );
};

export default Profile;